version: '3.1'

services:
  bind:
    image: genericdotbusiness/ns
    deploy:
      replicas: 2
    secrets:
      - source: generic_deploy_key
        uid: '0'
        gid: '0'
        mode: 0400
    ports:
    - "53:53/udp"
    - "53:53/tcp"
secrets:
  generic_deploy_key:
    external: true
