version: '2'

services:
  bind:
    container_name: generic-ns
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - /srv/docker/bind:/data
